-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 11-10-2024 a las 18:42:57
-- Versión del servidor: 10.4.28-MariaDB
-- Versión de PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `predicciones_db`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `encuestas`
--

CREATE TABLE `encuestas` (
  `id` int(11) NOT NULL,
  `marca_temporal` varchar(255) NOT NULL,
  `nombre_completo` varchar(255) NOT NULL,
  `correo_electronico` varchar(255) NOT NULL,
  `edad` varchar(255) NOT NULL,
  `genero` varchar(255) NOT NULL,
  `nombre_banco` varchar(255) NOT NULL,
  `calidad_servicio` varchar(255) NOT NULL,
  `satisfaccion_personal` varchar(255) NOT NULL,
  `personal_capacitado` varchar(255) NOT NULL,
  `frecuencia_uso` varchar(255) NOT NULL,
  `facilidad_canales_digitales` varchar(255) NOT NULL,
  `rapidez_respuesta` varchar(255) NOT NULL,
  `resolucion_primer_contacto` varchar(255) NOT NULL,
  `cambiar_banco` varchar(255) NOT NULL,
  `relacion_costo_beneficio` varchar(255) NOT NULL,
  `accesibilidad_personal` varchar(255) NOT NULL,
  `preferencia_atencion` varchar(255) NOT NULL,
  `comparacion_otros_bancos` varchar(255) NOT NULL,
  `vanguardia_tecnologia` varchar(255) NOT NULL,
  `seguridad_servicios` varchar(255) NOT NULL,
  `recomendaria_banco` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `encuestas`
--

INSERT INTO `encuestas` (`id`, `marca_temporal`, `nombre_completo`, `correo_electronico`, `edad`, `genero`, `nombre_banco`, `calidad_servicio`, `satisfaccion_personal`, `personal_capacitado`, `frecuencia_uso`, `facilidad_canales_digitales`, `rapidez_respuesta`, `resolucion_primer_contacto`, `cambiar_banco`, `relacion_costo_beneficio`, `accesibilidad_personal`, `preferencia_atencion`, `comparacion_otros_bancos`, `vanguardia_tecnologia`, `seguridad_servicios`, `recomendaria_banco`) VALUES
(1, '10/2/2024 13:02:51', 'Camila Marín Cardona ', '2006danelly@gmail.com', '18-35 años', 'Femenino', 'Banco de Occidente', 'Excelente', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Rápido', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'De acuerdo', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(2, '10/2/2024 16:19:06', 'María Camila ', '6dmariatoro@gmail.com', '18-35 años', 'Femenino', 'Banco de Occidente', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Semanalmente', 'Difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'Prefiero atención digital', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(3, '10/2/2024 13:43:33', 'Anderson Gomez ', 'afaridgomez003@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Neutral', 'Muy lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(4, '9/18/2024 16:40:57', 'Liseth Alarcón ', 'agudeloyuriliseth@gmail.com', '18-35 años', 'Femenino', 'Banco Davivienda', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Nunca', 'Muy rapido', 'Si, ya lo he hecho', 'Es lo mas importante', 'Muy bien informado/a', 'Muy accesible', 'Definitivamente si', '', '', '', '', ''),
(5, '10/3/2024 7:33:28', 'Maria Alejandra Navia Rodriguez ', 'alejanaviar98@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Normal', 'Algunas veces', 'No, pero he tenido malas experiencias', 'Neutral', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Neutral', 'Probablemente si'),
(6, '10/2/2024 19:49:57', 'Alejandro Valencia ', 'alejo662701@gmail.com', '36-45 años', 'Masculino', 'Banco Colpatria', 'Muy malo', 'Muy insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Lento', 'Rara vez', 'Si, ya lo he hecho', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(7, '10/2/2024 23:07:22', 'Adolfo León Gómez Prado ', 'algp1969@gmail.com', '46-55 años', 'Masculino', 'Banco de Occidente', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Rara vez', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Peor', 'Totalmente en desacuerdo', 'Inseguro/a', 'Probablemente no'),
(8, '10/2/2024 13:34:42', 'Doraxy Alvarado ', 'alvaradodoraxy2021@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Semanalmente', 'Muy fácil', 'Normal', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'De acuerdo', 'Accesible', 'Prefiero atención digital', 'Mejor', 'De acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(9, '10/2/2024 16:39:55', 'Isabella Daza ', 'alvarezhurtadoisa@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Neutral', 'Mensualmente', 'Fácil', 'Normal', 'Algunas veces', 'Tal vez', 'Neutral', 'Neutral', 'No tengo preferencia', 'Mejor', 'De acuerdo', 'Neutral', 'No lo se'),
(10, '10/2/2024 13:19:03', 'Daniela Zapata Jaramillo', 'amartevida630@gmail.com ', '18-35 años', 'Femenino', 'Banco de Bogotá ', 'Bueno', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Rápido', 'La mayoría de veces', 'No, pero he tenido malas experiencias', 'Neutral', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Seguro/a', 'Definitivamente si'),
(11, '10/3/2024 15:23:11', 'Andrés Felipe Herrera Rojas ', 'andres.fhr1991@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(12, '10/3/2024 12:12:04', 'Andres benitez ', 'Andresfelipebenitezmurilli@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Regular', 'Satisfecho', 'De acuerdo', 'Semanalmente', 'Fácil', 'Normal', 'Algunas veces', 'No, pero he tenido malas experiencias', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Peor', 'Neutral', 'Neutral', 'Probablemente si'),
(13, '10/2/2024 15:32:23', 'Paula', 'andrespaula94@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Muy malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Mucho peor', 'Totalmente en desacuerdo', 'Neutral', 'Probablemente no'),
(14, '10/2/2024 20:12:56', 'Carlos Andrés Prado ', 'andresprado731@hotmail.com', '18-35 años', 'Masculino', 'Banco Colpatria', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Semanalmente', 'Difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(15, '10/2/2024 17:53:15', 'Angélica paredes ', 'angelica.gissela.paredes@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Diariamente', 'Muy fácil', 'Muy rápido', 'Siempre', 'Tal vez', 'De acuerdo', 'Neutral', 'Prefiero atención presencial', 'Mucho mejor', 'Totalmente de acuerdo', 'Neutral', 'Definitivamente si'),
(16, '10/2/2024 13:21:07', 'Angélica María Jaramillo ', 'angelicajaramillo259@gmail.com', '46-55 años', 'Femenino', 'BBVA ', 'Bueno', 'Satisfecho', 'De acuerdo', 'Rara Vez', 'Fácil', 'Rápido', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'De acuerdo', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Seguro/a', 'Definitivamente si'),
(17, '10/2/2024 14:10:57', 'Angelica Maria Gomez Prado', 'angelmaria3014@gmail.com', '18-35 años', 'Femenino', 'Fundacion de la mujer ', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(18, '10/2/2024 15:01:31', 'Angie ', 'anligoca011091@outlook.com', '18-35 años', 'Femenino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Mensualmente', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(19, '10/2/2024 14:56:37', 'Por mi propia voluntad ', 'aracellyhurtado08@gmail.com', '46-55 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Muy difícil', 'Muy lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'Totalmente en desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(20, '10/2/2024 13:06:59', 'Ariherlyn Guadalupe Pérez García ', 'ariherlynp@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Totalmente de acuerdo', 'Semanalmente', 'Muy fácil', 'Normal', 'La mayoría de veces', 'Tal vez', 'De acuerdo', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Seguro/a', 'Definitivamente si'),
(21, '10/7/2024 14:53:54', 'Maria Erminia Girón Moreno ', 'asoprorozo10@gumail.com', '56-65 años', 'Femenino', 'Banco Agrario ', 'Regular', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Neutral', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'Totalmente en desacuerdo', 'Neutral', 'Probablemente no'),
(22, '10/2/2024 14:06:58', 'Aurora Gil Alarcón ', 'auroragilalarcon@gmail.com', '56-65 años', 'Femenino', 'Bancamia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(23, '10/8/2024 20:57:38', 'Lesvy Mayerli Benavides Gaita ', 'benavideslesvy@gmail.com ', '36-45 años', 'Femenino', 'Banco Davivienda', 'Regular', 'Insatisfecho', 'En desacuerdo', 'Diariamente', 'Neutral', 'Normal', 'Rara vez', 'No, pero he tenido malas experiencias', 'De acuerdo', 'Neutral', 'No tengo preferencia', 'Igual', 'De acuerdo', 'Neutral', 'Probablemente no'),
(24, '10/3/2024 3:46:23', 'Betty James García ', 'bettyjjg92@gmail.com', '18-35 años', 'Femenino', 'Caja social ', 'Malo', 'Insatisfecho', 'Totalmente en desacuerdo', 'Mensualmente', 'Difícil', 'Lento', 'Algunas veces', 'Si, lo estoy considerando', 'En desacuerdo', 'Neutral', 'Prefiero atención digital', 'Igual', 'En desacuerdo', 'Seguro/a', 'Probablemente no'),
(25, '10/2/2024 13:49:31', 'Bibiana García ', 'Binianagarcia@gmail.com ', '18-35 años', 'Femenino', 'Banco de Occidente', 'Bueno', 'Satisfecho', 'Neutral', 'Rara Vez', 'Neutral', 'Lento', 'Nunca', 'Tal vez', 'Neutral', 'Neutral', 'No tengo preferencia', 'Igual', 'Neutral', 'Neutral', 'Probablemente no'),
(26, '10/2/2024 13:55:32', 'Isabel Lenis', 'Bluebiker95@outlook.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Normal', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'Neutral', 'Neutral', 'Prefiero atención presencial', 'Igual', 'De acuerdo', 'Seguro/a', 'Probablemente si'),
(27, '10/2/2024 15:23:32', 'Si', 'boutiquejsbaby15@gmail.com', '46-55 años', 'Masculino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Neutral', 'Diariamente', 'Muy fácil', 'Normal', 'La mayoría de veces', 'Si, ya lo he hecho', 'En desacuerdo', 'Neutral', 'Prefiero atención presencial', 'Mejor', 'Totalmente de acuerdo', 'Neutral', 'Probablemente si'),
(28, '10/2/2024 12:53:28', 'Brayan Andrés López Marín ', 'brayanandreslopez64@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Rápido', 'Algunas veces', 'No, nunca he tenido malas experiencias', 'Neutral', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'Neutral', 'Seguro/a', 'Probablemente si'),
(29, '10/2/2024 15:05:24', 'Bueno ', 'brigitte.alarcon01@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Rara Vez', 'Fácil', 'Normal', 'La mayoría de veces', 'Tal vez', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Mejor', 'De acuerdo', 'Seguro/a', 'Probablemente si'),
(30, '10/7/2024 8:48:05', 'Samuel Caicedo Córdoba ', 'caicedocordobasamuel023@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'No, nunca he tenido malas experiencias', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(31, '10/2/2024 20:13:35', 'Carlos Arturo Gómez Escobar ', 'carlosarturogomezescobar8@gmail.com', '56-65 años', 'Masculino', 'Bancolombia', 'Malo', 'Insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Tal vez', 'Totalmente en desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(32, '10/5/2024 8:57:38', 'Carmen Elena Prado Silva', 'carmenpradosilva264@gmail.com ', '36-45 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Rara vez', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(33, '10/2/2024 13:35:13', 'Luisa Marina Casallas Díaz ', 'Casallasluisa11@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Diariamente', 'Muy fácil', 'Normal', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'De acuerdo', 'Muy accesible', 'No tengo preferencia', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(34, '10/3/2024 4:52:40', 'Andres salazar ', 'Chosita0610@gmail.com ', '46-55 años', 'Masculino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(35, '10/2/2024 19:31:24', 'claudia ximena marin suarez', 'clauximerin@golmait.com', '36-45 años', 'Femenino', 'Bancolombia', 'Regular', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Muy difícil', 'Lento', 'Rara vez', 'No, nunca he tenido malas experiencias', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Igual', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(36, '10/2/2024 18:06:20', 'Cristian Jesus Avella Mendoza', 'Cristianavella33@gmail.com ', '18-35 años', 'Masculino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Diariamente', 'Muy fácil', 'Muy rápido', 'Siempre', 'Si, ya lo he hecho', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención presencial', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(37, '10/3/2024 15:56:52', 'Danna Valentina Burbano ', 'dana08valentina@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Semanalmente', 'Muy fácil', 'Normal', 'Algunas veces', 'Tal vez', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Igual', 'Neutral', 'Seguro/a', 'Probablemente si'),
(38, '10/8/2024 11:50:30', 'David coral chamorro', 'Davidcoral7816@gmail.com', '46-55 años', 'Masculino', 'Banco de Occidente', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Fácil', 'Lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Igual', 'De acuerdo', 'Seguro/a', 'Probablemente no'),
(39, '10/2/2024 13:10:57', 'Dayron Esteban Muñoz Añasco ', 'dayronesteban7@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Regular', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Normal', 'La mayoría de veces', 'Tal vez', 'Neutral', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'Neutral', 'Seguro/a', 'Probablemente si'),
(40, '10/2/2024 17:13:32', 'Diana Gabriela Garcés Victoria ', 'dggarces52@gmail.com', '36-45 años', 'Femenino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(41, '10/2/2024 16:05:24', 'Responde ', 'dianafernandaquinteronieva@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Lento', 'Algunas veces', 'Si, lo estoy considerando', 'Neutral', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'Neutral', 'Inseguro/a', 'No lo se'),
(42, '10/2/2024 14:55:25', 'Diego ', 'diegorodri258@gmail.com', '18-35 años', 'Masculino', 'Banco Davivienda', 'Bueno', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'No, nunca he tenido malas experiencias', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(43, '10/8/2024 18:06:03', 'Diana Isabel Montaño Rodríguez ', 'dimontanoro85@gmail.com', '36-45 años', 'Femenino', 'Bancolombia', 'Regular', 'Satisfecho', 'Neutral', 'Mensualmente', 'Neutral', 'Normal', 'Algunas veces', 'Si, lo estoy considerando', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Igual', 'Neutral', 'Neutral', 'No lo se'),
(44, '10/3/2024 7:55:18', 'Daniela Zapata ', 'dzapataj.97@gmail.com', '18-35 años', 'Femenino', 'Banco Davivienda', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Muy lento', 'Rara vez', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(45, '10/2/2024 17:06:45', 'La atención es mala', 'elmigue0115@gmail.com', '46-55 años', 'Masculino', 'Bancolombia', 'Bueno', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'No lo se'),
(46, '10/2/2024 13:28:55', 'Jorge Esteban Benavides Muñoz ', 'estebanbm1005@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'En desacuerdo', 'Semanalmente', 'Difícil', 'Muy lento', 'Nunca', 'Tal vez', 'En desacuerdo', 'Poco accesible', 'Prefiero atención digital', 'Igual', 'En desacuerdo', 'Seguro/a', 'Probablemente no'),
(47, '10/4/2024 19:40:58', 'Farley Márquez Velez ', 'farleyee51@gmail.com', '46-55 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Neutral', 'Mensualmente', 'Fácil', 'Rápido', 'Siempre', 'No, nunca he tenido malas experiencias', 'De acuerdo', 'Accesible', 'No tengo preferencia', 'Igual', 'De acuerdo', 'Seguro/a', 'Probablemente si'),
(48, '10/3/2024 15:15:03', 'Fausto matituy murillo', 'faustomatituy7@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Totalmente de acuerdo', 'Semanalmente', 'Muy fácil', 'Muy rápido', 'Siempre', 'No, pero he tenido malas experiencias', 'De acuerdo', 'Accesible', 'Prefiero atención digital', 'Mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(49, '10/8/2024 18:10:23', 'Aliria Fernández ', 'fernandezaliria27@gmail.com ', '56-65 años', 'Femenino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'En desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(50, '10/2/2024 12:56:15', 'Flor Ospina ', 'fo2845353@gmail.com', '46-55 años', 'Femenino', 'Banco Davivienda', 'Excelente', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Difícil', 'Normal', 'Algunas veces', 'Tal vez', 'Neutral', 'Neutral', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Seguro/a', 'Probablemente si'),
(51, '10/4/2024 10:11:30', 'Fredy Vanegas Ávila ', 'fredyvanegas261@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Rara vez', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(52, '10/2/2024 13:27:02', 'Rubén Dario Gallego Gil ', 'gallegogil027@gmail.com', '36-45 años', 'Masculino', 'Banco avevillas ', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Semanalmente', 'Muy fácil', 'Muy rápido', 'Siempre', 'No, nunca he tenido malas experiencias', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención presencial', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(53, '10/2/2024 17:40:26', 'María Gomez', 'gecara2004@hotmail.com', '56-65 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'Totalmente en desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(54, '10/2/2024 15:16:29', 'Graciela reyes prado', 'gracielareyesprado@gmail.com', '18-35 años', 'Femenino', 'Banco Davivienda', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Muy difícil', 'Muy lento', 'Rara vez', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(55, '10/2/2024 13:24:32', 'Giselle S', 'gsalinas98@misena.edu.co', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Neutral', 'Mensualmente', 'Muy fácil', 'Normal', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'Neutral', 'Accesible', 'No tengo preferencia', 'Igual', 'De acuerdo', 'Seguro/a', 'Definitivamente si'),
(56, '10/2/2024 18:27:48', 'Harold Márquez ', 'haroldmarquez200@gmail.com', '46-55 años', 'Masculino', 'Bancolombia', 'Malo', 'Insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'En desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Mucho peor', 'Totalmente en desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(57, '10/8/2024 20:05:27', 'Felipe gallego arias', 'Hillmoney567@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(58, '10/2/2024 12:57:11', 'Ingrid Paola londoño ', 'ingridpaolalondonomarquez71@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Muy satisfecho', 'De acuerdo', 'Rara Vez', 'Fácil', 'Rápido', 'La mayoría de veces', 'No, pero he tenido malas experiencias', 'De acuerdo', 'Accesible', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Seguro/a', 'Definitivamente si'),
(59, '10/2/2024 12:55:31', 'Ivonne Cristina Cabal Franco ', 'ivonnecristinacabal98@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Semanalmente', 'Muy fácil', 'Muy rápido', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'De acuerdo', 'Muy accesible', 'Prefiero atención digital', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(60, '10/9/2024 1:12:08', 'Jairo', 'jairomarquez72@gmail.com', '46-55 años', 'Masculino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Mensualmente', 'Muy fácil', 'Muy rápido', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'Totalmente de acuerdo', 'Muy accesible', 'No tengo preferencia', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(61, '10/2/2024 13:33:55', 'Jeferson Andrés Lopez prado ', 'Jefersonandreslopezprado7@gmail.com', '18-35 años', 'Masculino', 'Avillas', 'Bueno', 'Muy satisfecho', 'Totalmente de acuerdo', 'Diariamente', 'Muy fácil', 'Muy rápido', 'Siempre', 'Si, ya lo he hecho', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención presencial', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(62, '10/2/2024 13:10:27', 'Jeferson Burbano', 'Jefferburba@gmail.com', '18-35 años', 'Masculino', 'Nu Bank', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Diariamente', 'Muy fácil', 'Muy rápido', 'Siempre', 'No, nunca he tenido malas experiencias', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención digital', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(63, '10/2/2024 21:39:38', 'Jhon prado', 'Jhonfredygesta@hotmail.com ', '36-45 años', 'Masculino', 'Bancolombia', 'Regular', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Mucho peor', 'En desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(64, '10/2/2024 20:21:43', 'José Fernando Valor Mañozca ', 'jjvalorm@gmail.com', '18-35 años', 'Masculino', 'Banco de Occidente', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'No, nunca he tenido malas experiencias', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(65, '10/2/2024 13:06:06', 'Jorge Echeverry', 'Jlecheverro@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Regular', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Normal', 'Algunas veces', 'Si, lo estoy considerando', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Igual', 'Neutral', 'Neutral', 'Probablemente no'),
(66, '10/5/2024 5:36:41', 'Joan sebastian Ramirez', 'Joanvelez019@gmail.com', '18-35 años', 'Masculino', 'Banco de Occidente', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Neutral', 'Lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Igual', 'Neutral', 'Neutral', 'No lo se'),
(67, '10/2/2024 13:28:19', 'Juan Restrepo ', 'juannrestrepo676@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Malo', 'Muy insatisfecho', 'Neutral', 'Mensualmente', 'Difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'Neutral', 'Neutral', 'No tengo preferencia', 'Peor', 'Neutral', 'Inseguro/a', 'Definitivamente no'),
(68, '10/3/2024 18:51:44', 'Lina Moreno', 'karenmorenomotoa@hotmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Neutral', 'Mensualmente', 'Neutral', 'Normal', 'Algunas veces', 'Tal vez', 'Neutral', 'Neutral', 'Prefiero atención presencial', 'Igual', 'Neutral', 'Seguro/a', 'No lo se'),
(69, '10/3/2024 20:34:31', 'Maria Gomez', 'katalinamadrid1306@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Regular', 'Satisfecho', 'Neutral', 'Semanalmente', 'Fácil', 'Lento', 'Algunas veces', 'Si, lo estoy considerando', 'De acuerdo', 'Accesible', 'Prefiero atención digital', 'Igual', 'De acuerdo', 'Seguro/a', 'No lo se'),
(70, '10/2/2024 13:36:48', 'Katerine guevara', 'Katerineguevaram@hotmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Regular', 'Insatisfecho', 'En desacuerdo', 'Semanalmente', 'Neutral', 'Lento', 'Algunas veces', 'Si, lo estoy considerando', 'En desacuerdo', 'Neutral', 'Prefiero atención presencial', 'Igual', 'Neutral', 'Inseguro/a', 'Probablemente no'),
(71, '10/2/2024 20:00:52', 'Katherine calero ', 'Katherinecaleroescobar@gmail.com', '18-35 años', 'Femenino', 'Banco Davivienda', 'Muy malo', 'Insatisfecho', 'En desacuerdo', 'Semanalmente', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'En desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Mucho peor', 'En desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(72, '10/2/2024 20:17:29', 'Leidy Johanna Gallo ', 'Leidyj0044@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Rara vez', 'Si, lo estoy considerando', 'En desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(73, '10/4/2024 15:14:53', 'Leidy Johana Galindo Sanchez ', 'leidyj1595@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Regular', 'Satisfecho', 'Neutral', 'Rara Vez', 'Neutral', 'Normal', 'Algunas veces', 'Tal vez', 'Neutral', 'Neutral', 'No tengo preferencia', 'Igual', 'Neutral', 'Neutral', 'No lo se'),
(74, '10/2/2024 16:34:05', 'Leidy Sánchez ', 'leidyvanesasanchezcerezo@gmail.com', '18-35 años', 'Femenino', 'Bogota', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Semanalmente', 'Difícil', 'Lento', 'Algunas veces', 'No, pero he tenido malas experiencias', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Igual', 'Neutral', 'Inseguro/a', 'No lo se'),
(75, '10/2/2024 14:00:38', 'Leydi joanna espinosa', 'leydiespinosa57. 5@gmail.com', '36-45 años', 'Femenino', 'Banco Colpatria', 'Malo', 'Insatisfecho', 'Neutral', 'Rara Vez', 'Difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(76, '10/2/2024 18:39:09', 'Andrés Mejia ', 'Limaandres695@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Normal', 'La mayoría de veces', 'No, pero he tenido malas experiencias', 'Neutral', 'Accesible', 'Prefiero atención digital', 'Mejor', 'Neutral', 'Seguro/a', 'Probablemente si'),
(77, '10/8/2024 13:00:50', 'Loren Montaño ', 'lorenmontano35@gmail.com', '18-35 años', 'Femenino', 'Banco de Bogotá ', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Muy difícil', 'Lento', 'Nunca', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(78, '10/2/2024 13:40:26', 'Luisa Dominguez', 'luisa1607dominguez@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'En desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'En desacuerdo', 'Muy inseguro/a', 'Probablemente no'),
(79, '10/2/2024 16:51:04', 'Ok', 'Luisfernandogallegogil@hotmail.com', '36-45 años', 'Masculino', 'Bnncond  bogota', 'Muy malo', 'Muy insatisfecho', 'En desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Muy accesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(80, '10/2/2024 19:55:11', 'Manuela Carvajal ', 'manuelaflor87@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'No, nunca he tenido malas experiencias', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(81, '10/2/2024 15:47:03', 'Sara ', 'Manuelamarquez86 ', '18-35 años', 'Femenino', 'Banco de Occidente', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'No, pero he tenido malas experiencias', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(82, '10/2/2024 17:01:48', 'Ok', 'marbranicogd@gmail.com', '36-45 años', 'Femenino', 'Bancolombia', 'Regular', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Difícil', 'Lento', 'Rara vez', 'Tal vez', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(83, '10/2/2024 21:41:18', 'Yazmin Agudelo ', 'mariachocho@gmail.com', '18-35 años', 'Femenino', 'Banco Colpatria', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(84, '10/3/2024 14:26:05', 'Angie Vanessa Montoya ', 'mariacundymi1234montoya@gmail.commaria', '18-35 años', 'Femenino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Mensualmente', 'Fácil', 'Muy rápido', 'Siempre', 'Si, ya lo he hecho', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Muy seguro/a', 'Probablemente si'),
(85, '10/2/2024 13:55:57', 'María de los angeles Buitrago ', 'mariadelosangelesbuitrago2@gmail.com', '36-45 años', 'Femenino', 'Bancolombia', 'Regular', 'Satisfecho', 'De acuerdo', 'Rara Vez', 'Neutral', 'Lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'En desacuerdo', 'Neutral', 'Prefiero atención presencial', 'Igual', 'Neutral', 'Neutral', 'No lo se'),
(86, '10/2/2024 21:44:36', 'Jesus María Gómez Ramirez ', 'mariaortiz3215@gmail.com', '36-45 años', 'Masculino', 'Banco de Occidente', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Rara vez', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(87, '10/2/2024 12:57:51', 'Maria de los angeles arce restrepo ', 'Mariarestreporodriguez6@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Rara Vez', 'Neutral', 'Lento', 'La mayoría de veces', 'Tal vez', 'Neutral', 'Accesible', 'Prefiero atención presencial', 'Igual', 'Neutral', 'Seguro/a', 'No lo se'),
(88, '10/7/2024 20:04:41', 'María Ruby Prado Montenegro ', 'mariarubyprado11@gmail.com', '56-65 años', 'Femenino', 'BBVA', 'Muy malo', 'Insatisfecho', 'Neutral', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Igual', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(89, '10/7/2024 11:09:08', 'Maricela Gironza Mamian', 'Maricelagironzamamian@gmail.com', '56-65 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'En desacuerdo', 'Mensualmente', 'Fácil', 'Lento', 'La mayoría de veces', 'Tal vez', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Igual', 'De acuerdo', 'Neutral', 'No lo se'),
(90, '10/7/2024 8:44:35', 'Maritza Miranda Vergara ', 'maritza.miranda2018@gmail.com', '46-55 años', 'Femenino', 'Bancolombia', 'Regular', 'Insatisfecho', 'Neutral', 'Mensualmente', 'Muy difícil', 'Lento', 'Algunas veces', 'Si, lo estoy considerando', 'Neutral', 'Poco accesible', 'Prefiero atención presencial', 'Igual', 'De acuerdo', 'Inseguro/a', 'Probablemente no'),
(91, '10/2/2024 16:53:40', 'Paola', 'marlen-971@hotmail.es', '18-35 años', 'Femenino', 'Bancolombia', 'Regular', 'Insatisfecho', 'Neutral', 'Mensualmente', 'Difícil', 'Lento', 'Algunas veces', 'Si, lo estoy considerando', 'En desacuerdo', 'Neutral', 'No tengo preferencia', 'Peor', 'Neutral', 'Neutral', 'Probablemente no'),
(92, '10/2/2024 16:32:28', 'No', 'marzalas09@gmail.com', '36-45 años', 'Femenino', 'Banco Davivienda', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Mucho mejor', 'Neutral', 'Neutral', 'No lo se'),
(93, '10/2/2024 15:18:05', 'Mayra Alejandra nieto ', 'Mayrabieto1106@gmail.com', '36-45 años', 'Femenino', 'Banco Colpatria', 'Regular', 'Insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Neutral', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Peor', 'De acuerdo', 'Neutral', 'Probablemente no'),
(94, '10/2/2024 14:42:10', 'Si', 'Mello-89@hotmail.com', '18-35 años', 'Masculino', 'Banco Colpatria', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Lento', 'Algunas veces', 'Tal vez', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Igual', 'Neutral', 'Muy inseguro/a', 'Probablemente no'),
(95, '10/3/2024 14:33:29', 'Millerlandy Molina', 'Millerlandymolina@gmail.com', '18-35 años', 'Femenino', 'Banco Davivienda', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Semanalmente', 'Neutral', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(96, '10/2/2024 13:13:27', 'Eider Montejo Benavides ', 'montejoeider154@gmail.com', '18-35 años', 'Masculino', ' Banco de Bogotá ', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Semanalmente', 'Muy fácil', 'Muy rápido', 'Siempre', 'No, nunca he tenido malas experiencias', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención digital', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(97, '10/2/2024 22:47:29', 'Marino sanchez prado', 'msanchezp1971@gmail.com', '46-55 años', 'Masculino', 'Banco Davivienda', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, ya lo he hecho', 'Totalmente en desacuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(98, '10/2/2024 20:28:11', 'Marino sanchez cerezo', 'Mscnito@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Semanalmente', 'Muy difícil', 'Muy lento', 'Nunca', 'No, pero he tenido malas experiencias', 'Totalmente en desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(99, '10/2/2024 20:31:59', 'Nalliby Sandoval ', 'Nallibys@hotmail.com', '46-55 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'Totalmente en desacuerdo', 'Semanalmente', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Mucho peor', 'En desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(100, '10/2/2024 14:41:38', 'John alexander navas', 'Navasjohn07@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Rara Vez', 'Fácil', 'Rápido', 'La mayoría de veces', 'Tal vez', 'Neutral', 'Accesible', 'Prefiero atención presencial', 'Igual', 'De acuerdo', 'Seguro/a', 'No lo se'),
(101, '10/2/2024 12:53:56', 'Maira Alejandra Orozco ', 'orozcomayra120@gmail.com', '18-35 años', 'Femenino', 'Banco Colpatria', 'Excelente', 'Muy satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Rápido', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'De acuerdo', 'Accesible', 'No tengo preferencia', 'Mejor', 'De acuerdo', 'Seguro/a', 'Definitivamente si'),
(102, '10/5/2024 11:12:40', 'Oscar gil', 'Oscarwil75@gmail.com', '46-55 años', 'Masculino', 'Banco Davivienda', 'Regular', 'Satisfecho', 'De acuerdo', 'Semanalmente', 'Fácil', 'Rápido', 'La mayoría de veces', 'Tal vez', 'Neutral', 'Neutral', 'No tengo preferencia', 'Igual', 'Neutral', 'Seguro/a', 'No lo se'),
(103, '10/2/2024 15:01:10', 'Obligatoriá', 'Pájaro-54@hotmail.es ', '56-65 años', 'Masculino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Muy difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(104, '10/4/2024 15:01:37', 'Sandra patricia larrahondo', 'Patico2483@gmail.com', '36-45 años', 'Femenino', 'Bogota', 'Malo', 'Muy insatisfecho', 'En desacuerdo', 'Mensualmente', 'Neutral', 'Lento', 'Nunca', 'Si, lo estoy considerando', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'Neutral', 'Inseguro/a', 'Probablemente no'),
(105, '10/2/2024 15:05:54', 'Baja calidad de servicio', 'patric1976d@gmail.com', '46-55 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Diariamente', 'Difícil', 'Muy lento', 'Rara vez', 'Si, lo estoy considerando', 'Totalmente en desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(106, '10/2/2024 16:49:23', 'Persides cerezo', 'Persidescerezocastillo@gmail.com', '46-55 años', 'Femenino', 'Bancolombia', 'Malo', 'Insatisfecho', 'En desacuerdo', 'Mensualmente', 'Difícil', 'Lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(107, '10/2/2024 20:11:45', 'Lesly Vanessa Ramirez Tobón ', 'ramireztobonleslyvanessa@gmail.com', '18-35 años', 'Femenino', 'Banco Davivienda', 'Muy malo', 'Muy insatisfecho', 'Totalmente en desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Nunca', 'Si, lo estoy considerando', 'Totalmente de acuerdo', 'Muy inaccesible', 'No tengo preferencia', 'Mucho peor', 'Totalmente en desacuerdo', 'Muy inseguro/a', 'Definitivamente no'),
(108, '10/3/2024 19:28:41', 'Yaneth Restuccia ', 'restucciyaneth@gmail.com', '46-55 años', 'Femenino', 'Bancolombia', 'Excelente', 'Satisfecho', 'De acuerdo', 'Diariamente', 'Fácil', 'Rápido', 'Siempre', 'Tal vez', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención digital', 'Mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(109, '10/2/2024 15:08:14', 'Si es tenido inconvenientes ', 'reyesbravodaniel0510@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Regular', 'Satisfecho', 'De acuerdo', 'Rara Vez', 'Fácil', 'Lento', 'Rara vez', 'Tal vez', 'En desacuerdo', 'Poco accesible', 'Prefiero atención presencial', 'Igual', 'De acuerdo', 'Neutral', 'Probablemente si'),
(110, '10/3/2024 6:47:24', 'Maria leidy sanchez vasquez ', 'Sanchezmariale1991@gmail.com', '18-35 años', 'Femenino', 'Banco Colpatria', 'Malo', 'Muy insatisfecho', 'En desacuerdo', 'Rara Vez', 'Difícil', 'Lento', 'Rara vez', 'Tal vez', 'En desacuerdo', 'Poco accesible', 'No tengo preferencia', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Definitivamente no'),
(111, '10/2/2024 15:43:31', 'Sara Beltran', 'Saramanuelabeltranv@gmail.com', '18-35 años', 'Femenino', 'Nequi', 'Bueno', 'Insatisfecho', 'Neutral', 'Diariamente', 'Fácil', 'Normal', 'La mayoría de veces', 'Si, lo estoy considerando', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Igual', 'De acuerdo', 'Seguro/a', 'Probablemente si'),
(112, '10/2/2024 15:54:38', '.', 'sarapiedrahita230@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Neutral', 'Semanalmente', 'Muy fácil', 'Normal', 'Algunas veces', 'No, pero he tenido malas experiencias', 'Neutral', 'Neutral', 'Prefiero atención presencial', 'Mejor', 'De acuerdo', 'Seguro/a', 'No lo se'),
(113, '10/2/2024 13:01:29', 'SEBASTIÁN CAICEDO QUIÑONEZ ', 'scaicedo776@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Regular', 'Insatisfecho', 'Neutral', 'Semanalmente', 'Muy fácil', 'Rápido', 'Algunas veces', 'Tal vez', 'De acuerdo', 'Accesible', 'No tengo preferencia', 'Mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Probablemente si'),
(114, '10/2/2024 16:09:42', 'Lina ayala ', 'sebastianeasport@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Muy malo', 'Insatisfecho', 'Totalmente en desacuerdo', 'Semanalmente', 'Difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'Neutral', 'Muy inaccesible', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Inseguro/a', 'Probablemente no'),
(115, '10/3/2024 14:19:56', 'LINA ROBAYO RODRIGUEZ', 'servicioalclientevalle@oxigenosdelsur.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Semanalmente', 'Muy fácil', 'Muy rápido', 'La mayoría de veces', 'Si, lo estoy considerando', 'De acuerdo', 'Accesible', 'Prefiero atención digital', 'Mejor', 'De acuerdo', 'Seguro/a', 'Probablemente si'),
(116, '10/2/2024 13:54:39', 'Yerly Sofia Sterling Buitrago ', 'sofiasterling84@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Regular', 'Insatisfecho', 'Neutral', 'Mensualmente', 'Difícil', 'Lento', 'Rara vez', 'Si, lo estoy considerando', 'Neutral', 'Neutral', 'Prefiero atención presencial', 'Peor', 'En desacuerdo', 'Neutral', 'Probablemente no'),
(117, '10/2/2024 14:39:38', 'Por mi voluntad ', 'Sonia_130471@hotmail.com', '46-55 años', 'Femenino', 'Banco Colpatria', 'Malo', 'Muy insatisfecho', 'En desacuerdo', 'Rara Vez', 'Muy difícil', 'Muy lento', 'Rara vez', 'No, pero he tenido malas experiencias', 'Totalmente en desacuerdo', 'Muy inaccesible', 'Prefiero atención presencial', 'Peor', 'Neutral', 'Inseguro/a', 'Probablemente no'),
(118, '10/2/2024 13:49:30', 'Soraya Isanoa ', 'sorayaisanoa@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Fácil', 'Normal', 'La mayoría de veces', 'No, nunca he tenido malas experiencias', 'Neutral', 'Accesible', 'Prefiero atención presencial', 'Igual', 'De acuerdo', 'Seguro/a', 'Probablemente si'),
(119, '10/2/2024 19:15:55', 'Stiven colorado ', 'stivenchoo@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Bueno', 'Satisfecho', 'Totalmente de acuerdo', 'Mensualmente', 'Fácil', 'Normal', 'La mayoría de veces', 'No, pero he tenido malas experiencias', 'De acuerdo', 'Muy accesible', 'Prefiero atención digital', 'Mucho mejor', 'Totalmente de acuerdo', 'Seguro/a', 'Probablemente si'),
(120, '10/2/2024 16:00:44', 'Victoria Valero ', 'Valerovictoria18@gmail.com ', '18-35 años', 'Femenino', 'Bancolombia', 'Bueno', 'Satisfecho', 'En desacuerdo', 'Rara Vez', 'Neutral', 'Normal', 'Rara vez', 'Tal vez', 'De acuerdo', 'Neutral', 'No tengo preferencia', 'Igual', 'Neutral', 'Neutral', 'Probablemente si'),
(121, '10/2/2024 13:42:16', 'Yader Andrey mutis montealegre ', 'yadermutis@icloud.com', '18-35 años', 'Masculino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Mensualmente', 'Muy fácil', 'Muy rápido', 'Siempre', 'Si, ya lo he hecho', 'Totalmente de acuerdo', 'Muy accesible', 'Prefiero atención presencial', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(122, '10/5/2024 11:34:23', 'Jeisson Alexander Zúñiga ', 'yeisonzuniga75@gmail.com', '18-35 años', 'Masculino', 'Bancolombia', 'Excelente', 'Muy satisfecho', 'Totalmente de acuerdo', 'Semanalmente', 'Muy fácil', 'Muy rápido', 'Siempre', 'No, nunca he tenido malas experiencias', 'Totalmente de acuerdo', 'Muy accesible', 'No tengo preferencia', 'Mucho mejor', 'Totalmente de acuerdo', 'Muy seguro/a', 'Definitivamente si'),
(123, '10/2/2024 12:54:33', 'Yuliana Castro Dominguez ', 'yulianadominguez048@gmail.com', '18-35 años', 'Femenino', 'Bancolombia', 'Regular', 'Insatisfecho', 'Neutral', 'Semanalmente', 'Fácil', 'Normal', 'Algunas veces', 'No, pero he tenido malas experiencias', 'De acuerdo', 'Neutral', 'Prefiero atención digital', 'Igual', 'De acuerdo', 'Inseguro/a', 'Probablemente si'),
(124, '10/2/2024 16:31:56', '.', 'zuluaagaa1999@gmail.com', '18-35 años', 'Masculino', 'Av villas', 'Bueno', 'Satisfecho', 'De acuerdo', 'Mensualmente', 'Neutral', 'Normal', 'Algunas veces', 'No, nunca he tenido malas experiencias', 'Neutral', 'Neutral', 'Prefiero atención digital', 'Igual', 'Neutral', 'Neutral', 'No lo se');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `encuestas`
--
ALTER TABLE `encuestas`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `correo_electronico` (`correo_electronico`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `encuestas`
--
ALTER TABLE `encuestas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=125;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
